from . import xg
from . import aec
from . import aec_gan
from . import aec_gan_xg
from . import aec_gan_stack
from . import datatype_discr
from . import krauss
from . import ganmore
from . import sk_tpot
from . import disentangle
from . import disentangle_kfold
from . import disentanglegan
from . import vae
from . import moddisengan
from . import moddisengan2
from . import moddisengan3
from . import tsne
from . import tsne_simple
from . import simple
from . import res
from . import highway
from . import highway2
from . import simplekfold
from . import tsne_simplekfold
